export type ColorScheme = 'danger' | 'supernova' | 'nebula-blue' | 'cobalt' | 'comet' | 'black' | 'white';

export type Color =
  | ColorScheme
  | 'supernova'
  | 'supernova-dark'
  | 'nebula-blue-shades'
  | 'nebula-blue'
  | 'nebula-blue-dark'
  | 'cobalt-dark'
  | 'cobalt'
  | 'comet'
  | 'comet-dark'
  | 'additional-link'
  | 'success-dark'
  | 'success-light'
  | 'error-light'
  | 'error'
  | 'error-dark'
  | 'alert-light'
  | 'alert-dark'
  | 'info-light'
  | 'info-dark'
  | 'darkest'
  | 'darker'
  | 'neutral'
  | 'disabled-light'
  | 'light'
  | 'lighter'
  | 'white'
  | 'grey-1'
  | 'grey-2'
  | 'grey-3'
  | 'grey-4';
