/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Variant } from "./types/common/variants";
import { ColorScheme } from "./types/common/color-scheme";
import { UnitString } from "./types/common/unit-string";
import { Size } from "./types/common/size";
export { Variant } from "./types/common/variants";
export { ColorScheme } from "./types/common/color-scheme";
export { UnitString } from "./types/common/unit-string";
export { Size } from "./types/common/size";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SolarisButton {
        "colorScheme": ColorScheme;
        "fullWidth"?: boolean;
        "href": string;
        "radius"?: UnitString;
        "size"?: Size;
        "variant": Variant;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSolarisButtonElement extends Components.SolarisButton, HTMLStencilElement {
    }
    var HTMLSolarisButtonElement: {
        prototype: HTMLSolarisButtonElement;
        new (): HTMLSolarisButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "solaris-button": HTMLSolarisButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SolarisButton {
        "colorScheme"?: ColorScheme;
        "fullWidth"?: boolean;
        "href"?: string;
        "radius"?: UnitString;
        "size"?: Size;
        "variant"?: Variant;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "solaris-button": SolarisButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "solaris-button": LocalJSX.SolarisButton & JSXBase.HTMLAttributes<HTMLSolarisButtonElement>;
        }
    }
}
