/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SolarisColumn {
    }
}
declare global {
    interface HTMLSolarisColumnElement extends Components.SolarisColumn, HTMLStencilElement {
    }
    var HTMLSolarisColumnElement: {
        prototype: HTMLSolarisColumnElement;
        new (): HTMLSolarisColumnElement;
    };
    interface HTMLElementTagNameMap {
        "solaris-column": HTMLSolarisColumnElement;
    }
}
declare namespace LocalJSX {
    interface SolarisColumn {
    }
    interface IntrinsicElements {
        "solaris-column": SolarisColumn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "solaris-column": LocalJSX.SolarisColumn & JSXBase.HTMLAttributes<HTMLSolarisColumnElement>;
        }
    }
}
